# Generated by Django 5.0.3 on 2024-03-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, verbose_name='내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
            ],
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='댓글')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
            ],
        ),
        # migrations.CreateModel(
        #     name='FeedImage',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('image_url', models.ImageField(upload_to='feed/image', verbose_name='피드 이미지')),
        #     ],
        # ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='태그명')),
            ],
        ),
    ]
