# Generated by Django 5.0.3 on 2024-03-16 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='tag',
            field=models.ManyToManyField(related_name='tag_feeds', to='feeds.hashtag', verbose_name='태그명'),
        ),
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='feed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='feeds.feed', verbose_name='피드'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
            preserve_default=False,
        ),
    #     migrations.CreateModel(
    #         name='FeedImage',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('image_url', models.ImageField(upload_to='feed/image', verbose_name='피드 이미지')),
    #             ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.feed', verbose_name='피드')),
    #         ],
    #     ),
    ]
