# Generated by Django 5.0.3 on 2024-03-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feed_tag_feed_user_feedcomment_feed_feedcomment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='feed/image', verbose_name='피드 이미지')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.feed', verbose_name='피드')),
            ],
        ),
    ]
