# Generated by Django 5.0.3 on 2024-03-10 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=10, verbose_name='이름')),
                ('user_id', models.CharField(max_length=64, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('profile_image', models.ImageField(blank=True, upload_to='users/profile', verbose_name='프로필 이미지')),
                ('short_description', models.TextField(blank=True, verbose_name='소개글')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('login_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='FollowRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follow_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_relation', to=settings.AUTH_USER_MODEL, verbose_name='팔로우 요청한 사용자')),
                ('follow_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relation', to=settings.AUTH_USER_MODEL, verbose_name='팔로우 요청의 대상')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='users.FollowRelation', to=settings.AUTH_USER_MODEL, verbose_name='내가 팔로잉한 사람들'),
        ),
    ]
