# Generated by Django 5.0.3 on 2024-03-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='회원가입 일시'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='최근 로그인 일시'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='최근 수정 일시'),
        ),
    ]
