# Generated by Django 5.0.3 on 2024-03-19 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_default_main_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_main_page',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='기본 메인 페이지'),
        ),
    ]
