# Generated by Django 5.0.3 on 2024-04-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_searchkeyword'),
        ('users', '0005_alter_user_like_feeds_alter_user_like_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_keyword',
            field=models.ManyToManyField(related_name='keyword_user', to='posts.searchkeyword', verbose_name='유저 키워드'),
        ),
    ]
