# Generated by Django 5.0.3 on 2024-04-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_searchkeyword_keyword_relation'),
        ('users', '0006_user_search_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='search_keyword',
            field=models.ManyToManyField(related_name='keyword_user', to='posts.searchkeyword', verbose_name='사용자 검색 키워드'),
        ),
    ]
