# Generated by Django 5.0.3 on 2024-04-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_searchkeyword_keyword_relation'),
        ('users', '0007_alter_user_search_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='search_keyword',
            field=models.ManyToManyField(blank=True, related_name='keyword_user', to='posts.searchkeyword', verbose_name='사용자 검색 키워드'),
        ),
    ]
