# Generated by Django 5.0.3 on 2024-04-15 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_searchkeyword_keyword_relation'),
        ('users', '0008_alter_user_search_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='search_keyword',
        ),
        migrations.CreateModel(
            name='UserSearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_at', models.DateTimeField(auto_now_add=True, verbose_name='최근 조회 일시')),
                ('search_keyword', models.ManyToManyField(blank=True, related_name='keyword_user', to='posts.searchkeyword', verbose_name='사용자 검색 키워드')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
