# Generated by Django 5.0.3 on 2024-03-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='댓글')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
            ],
        ),
        # migrations.CreateModel(
        #     name='PostImage',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('image_url', models.ImageField(blank=True, upload_to='post/image', verbose_name='포스트 이미지')),
        #     ],
        # ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('context', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('tag', models.ManyToManyField(related_name='tag_posts', to='feeds.hashtag', verbose_name='태그명')),
            ],
        ),
    ]
