# Generated by Django 5.0.3 on 2024-03-27 13:33

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='context',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='내용'),
        ),
        migrations.CreateModel(
            name='PreviewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='제목')),
                ('content', markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='내용')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='태그')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='PreviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='post/preview', verbose_name='포스트 미리보기 이미지')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.previewpost', verbose_name='미리보기 이미지')),
            ],
        ),
    ]
