# Generated by Django 5.0.3 on 2024-04-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_feedimage'),
        ('posts', '0006_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_posts', to='feeds.hashtag', verbose_name='태그명'),
        ),
    ]
