# Generated by Django 5.0.3 on 2024-04-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='post/image', verbose_name='포스트 미리보기 이미지'),
        ),
    ]
