# Generated by Django 5.0.3 on 2024-04-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_previewimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='preview_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.previewpost', verbose_name='미리보기 이미지'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='포스트 이미지'),
        ),
        migrations.DeleteModel(
            name='PreviewImage',
        ),
    ]
