# Generated by Django 5.0.3 on 2024-04-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postimage_preview_post_alter_postimage_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='검색 키워드')),
                ('count', models.IntegerField(default=1, verbose_name='검색 횟수')),
                ('keyword_relation', models.ManyToManyField(related_name='keyword_relation', to='posts.searchkeyword', verbose_name='연관 키워드')),
            ],
        ),
    ]
