# Generated by Django 5.0.3 on 2024-04-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_searchkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchkeyword',
            name='keyword_relation',
            field=models.ManyToManyField(to='posts.searchkeyword', verbose_name='연관 키워드'),
        ),
    ]
