# Generated by Django 5.0.3 on 2024-04-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_searchkeyword_keyword_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchkeyword',
            name='keyword_relation',
            field=models.ManyToManyField(blank=True, to='posts.searchkeyword', verbose_name='연관 키워드'),
        ),
    ]
